"""Add cooking preferences

Revision ID: 9a09c0380c52
Revises: 
Create Date: 2025-03-31 17:46:27.659546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a09c0380c52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooking_methods', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('kitchen_tools', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('kitchen_tools')
        batch_op.drop_column('cooking_methods')

    # ### end Alembic commands ###
